import type { TuningMeasurementState } from '../tuning/tuningMeasurement';
import type { CompanionCommand } from './companionProtocol';

type Props = { measurement: { phase: string; sampleCount: number; state: TuningMeasurementState | null }; disabled: boolean; onCommand: (command: Omit<CompanionCommand, 'id' | 'carId' | 'profileKey'>) => Promise<boolean> };
const n = (value: number | undefined, digits = 1) => value === undefined || !Number.isFinite(value) ? '—' : value.toFixed(digits);
const phaseAllows = (phase: string, action: string) => action === 'start' ? phase === 'idle' : action === 'pause_resume' ? ['collecting', 'paused'].includes(phase) : ['invalidated', 'paused', 'collecting', 'complete'].includes(phase);
export default function CompanionMeasurement({ measurement, disabled, onCommand }: Props) {
  const state = measurement.state;
  return <div className="companion-panel"><h2>Engine measurement</h2><div className="companion-stat-grid"><Stat label="Phase" value={measurement.phase} /><Stat label="Samples" value={String(measurement.sampleCount)} /><Stat label="Accepted" value={state ? n(state.acceptedMs / 1000, 1) : '—'} unit="s" /><Stat label="Bins" value={state ? String(state.bins.length) : '0'} /><Stat label="Guidance" value={state?.guidance || '—'} /><Stat label="Peak power" value={state?.observedPeakPower ? `${n(state.observedPeakPower.value)} W @ ${n(state.observedPeakPower.rpm, 0)} rpm` : '—'} /><Stat label="Peak torque" value={state?.observedPeakTorque ? `${n(state.observedPeakTorque.value)} Nm @ ${n(state.observedPeakTorque.rpm, 0)} rpm` : '—'} /></div><div className="d-flex gap-2 mt-3 flex-wrap"><Action label="Start" disabled={disabled || !phaseAllows(measurement.phase, 'start')} onClick={() => onCommand({ kind: 'measurement', action: 'start' })} /><Action label="Pause / resume" disabled={disabled || !phaseAllows(measurement.phase, 'pause_resume')} onClick={() => onCommand({ kind: 'measurement', action: 'pause_resume' })} /><Action label="Restart" disabled={disabled || !phaseAllows(measurement.phase, 'restart')} onClick={() => onCommand({ kind: 'measurement', action: 'restart' })} /><Action label="Finish" disabled={disabled || measurement.phase !== 'complete'} onClick={() => onCommand({ kind: 'measurement', action: 'finish' })} /></div></div>;
}
function Stat({ label, value, unit = '' }: { label: string; value: string; unit?: string }) { return <div><span className="companion-stat-label">{label}</span><strong>{value}{unit && ` ${unit}`}</strong></div>; }
function Action({ label, disabled, onClick }: { label: string; disabled: boolean; onClick: () => Promise<boolean> }) { return <button className="btn btn-outline-secondary flex-grow-1" disabled={disabled} onClick={() => void onClick()}>{label}</button>; }
