export interface RoadIdentity { ordinal: number; performanceIndex: number; drivetrain: number }
export interface RoadEvent { name: string; format: 'circuit' | 'sprint'; driverAssists: string; conditions: string }
export interface RoadBase { id: string; workflowId: string; createdAt: number; schema: 'road-workflow/v1' }
export interface RoadWorkflow extends RoadBase { kind: 'workflow'; identity: RoadIdentity; identitySource: string; carName: string; configuration: string; gameBuild?: string; event: RoadEvent; recommendation?: { inputSnapshot: Record<string, unknown> } }
export interface RoadSetting { value: number; unit: string; minimum?: number; maximum?: number; step?: number; source: string }
export interface RoadSetup extends RoadBase { kind: 'setup'; label: string; fields: Record<string, RoadSetting>; confirmationScope: string; source: string; baselineSetupId: string | null; basisSetupId?: string; basisRunId?: string; targetParameter?: string; status?: string }
export interface RoadRun extends RoadBase { kind: 'run'; setupId: string; sessionId: string; settingsConfirmed: boolean; identity: RoadIdentity; otherSettings: string; tires: string; conditions: string; driverAssists: string }
export interface Distribution { observedSeconds: number; mean: number | null; p05: number | null; p50: number | null; p95: number | null }
export interface RoadWheel { temperatureC: Distribution; startTemperatureC: number | null; endTemperatureC: number | null; temperatureChangeC: number | null; nearCompression: { count: number | null; seconds: number | null; observedSeconds: number }; normalizedAngle: Distribution }
export interface RoadSummary extends RoadBase { kind: 'summary'; runId: string; sessionId: string; recording: { endReason: string; droppedSamples?: number; failedWrites?: number; incompletePersistence?: boolean }; observations: { channels?: Record<string, Distribution>; sampleCount: number; quality: { observedSeconds: number; gapSeconds: number }; wheels: Record<string, RoadWheel>; laps: { lapNumber: number; complete: boolean; lapTimeSeconds: number | null; lapTimeSource: string }[] } }
export interface RoadFinish extends RoadBase { kind: 'finish'; runId: string; timeSeconds: number; clean: string; source: string }
export interface RoadReport extends RoadBase { kind: 'comparison'; baselineRunIds: string[]; candidateRunIds: string[]; baselineSetupId: string; candidateSetupId: string; conclusion: string; reasons: string[]; methodVersion: string; evidenceLevel: string; independentRuns: { baseline: number; candidate: number }; time: { medianChangeSeconds: number | null; baselineSeconds: number[]; candidateSeconds: number[]; repeatedDirectionConsistent: boolean }; thermalStart: { status: string; changeC: (number | null)[] }; local: { segments?: RoadSegment[]; routeStatus: string; baselineCoverage: number; candidateCoverage: number; matchedDrivingConditions: number; meanNormalizedAngleChange: number | null }; limitations: string[] }
export interface RoadDecision extends RoadBase { kind: 'decision'; reportId: string; choice: string; setupId: string; status: string }
export interface RoadSegment { index: number; fromMeters: number; toMeters: number; matchedLocations: number; angleLocations: number; meanNormalizedAngleChange: number | null; meanTemperatureChangeC: (number | null)[] }
export interface RoadFeedback extends RoadBase { kind: 'feedback'; baselineRunId: string; hypothesis: string; source: string; baselineSetupId: string }
export interface RoadVehicleInputs extends RoadBase { kind: 'vehicle-inputs'; fields: Record<string, { value: number; unit: string; source: string }>; confirmationScope: string }
export type RoadDocument = RoadWorkflow | RoadSetup | RoadRun | RoadSummary | RoadFinish | RoadReport | RoadDecision | RoadFeedback | RoadVehicleInputs;
export interface RoadLive { identity: RoadIdentity | null; fresh: boolean; source: string; activeRun: { id: string; workflowId: string } | null; sampleCount: number; state: string; error: string | null }
export const documentsOf = <K extends RoadDocument['kind']>(docs: RoadDocument[], kind: K) => docs.filter((d): d is Extract<RoadDocument, { kind: K }> => d.kind === kind);
