// Reproducible asset import. Run: node frontend/scripts/vendor-rhine.mjs D:/RhineLabUI
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const source = path.resolve(process.argv[2] || '../RhineLabUI');
const frontend = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const revision = '3664b4abe3b7e852c7022a261e2d66d8f2e8c667';
if (execFileSync('git', ['-C', source, 'rev-parse', 'HEAD'], { encoding: 'utf8' }).trim() !== revision) {
  throw new Error(`Expected RhineLabUI ${revision}; review upstream changes before importing.`);
}
const hash = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const files = [];
function write(relative, bytes, original) {
  relative = relative.replace('public/fonts/', 'public/assets/rhine/fonts/').replace('public/licenses/', 'public/assets/rhine/licenses/');
  // Match Git checkout bytes on Windows and Linux; never alter font/PDF binaries.
  if (/\.(css|txt|md|json)$/.test(relative)) bytes = Buffer.from(bytes.toString().replaceAll('\r\n', '\n'));
  const destination = path.join(frontend, relative);
  fs.mkdirSync(path.dirname(destination), { recursive: true });
  fs.writeFileSync(destination, bytes);
  files.push({ path: relative, sha256: hash(bytes), ...(original ? { source: original } : {}) });
}
const fontBase = 'public/fonts/misans-webfont-4.3.1';
const fontSource = JSON.parse(fs.readFileSync(path.join(source, fontBase, 'source.json'), 'utf8'));
for (const entry of fontSource.files.filter(file => /^(regular|demibold)\//.test(file.path))) {
  const relative = `${fontBase}/${entry.path}`;
  const bytes = fs.readFileSync(path.join(source, relative));
  if (hash(bytes) !== entry.sha256) throw new Error(`Font integrity mismatch: ${relative}`);
  write(relative, bytes, relative);
}
const css = fs.readFileSync(path.join(source, 'src/fonts.css'), 'utf8').split('\n')
  .filter(line => /font-weight:(400|600);/.test(line)).join('\n').replaceAll('font-family:"MiSans"', 'font-family:"Rhine MiSans"').replaceAll('/fonts/', '/assets/rhine/fonts/');
write('src/styles/fonts/rhine-misans.css', `/* MiSans 4.003 / misans-webfont 4.3.1. Generated by scripts/vendor-rhine.mjs. */\n${css}\n`);
for (const name of ['MiSans-license.pdf', 'NOTICE.txt']) {
  let bytes = fs.readFileSync(path.join(source, 'public/fonts', name));
  if (name === 'NOTICE.txt') bytes = Buffer.concat([bytes, Buffer.from('\nHorizonTuner retains only unmodified regular (400) and demibold (600) shards.\nTooling license: misans-webfont-4.3.1/TOOLING-LICENSE-APACHE-2.0.txt\nTooling source: https://github.com/mobeicanyue/misans-webfont/blob/main/LICENSE\n')]);
  write(`public/fonts/${name}`, bytes, `public/fonts/${name}`);
}
write(`${fontBase}/UPSTREAM-README.md`, fs.readFileSync(path.join(source, fontBase, 'UPSTREAM-README.md')));
write(`${fontBase}/source.json`, JSON.stringify({ ...fontSource, cssChanges: '400/600 only; family renamed Rhine MiSans; original WOFF2 bytes unchanged.', files: fontSource.files.filter(f => /^(regular|demibold)\//.test(f.path)) }, null, 2) + '\n');
write('public/licenses/RhineLabUI-MIT.txt', fs.readFileSync(path.join(source, 'LICENSE')), 'LICENSE');

write('public/assets/rhine/SOURCE.json', JSON.stringify({ repository: 'https://github.com/LBEILC/RhineLabUI', revision, files }, null, 2) + '\n');
console.log(`Imported ${files.length} font, attribution and provenance files.`);
