export interface DriftIdentity { ordinal: number; performanceIndex: number; drivetrain: number }
export interface DriftEvent { name: string; format: 'zone' | 'drift-course'; driverAssists: string; conditions: string }
export interface DriftBase { id: string; workflowId: string; createdAt: number; schema: 'drift-workflow/v1' }
export interface DriftWorkflow extends DriftBase { kind: 'workflow'; identity: DriftIdentity; identitySource: string; carName: string; configuration: string; event: DriftEvent }
export interface DriftSetting { value: number; unit: string; minimum: number; maximum: number; step: number; source: string }
export interface DriftSetup extends DriftBase { kind: 'setup'; label: string; fields: Record<string, DriftSetting>; confirmationScope: string; source: string; baselineSetupId: string | null; basisSetupId?: string; basisRunId?: string; targetParameter?: string; status?: string }
export interface DriftRun extends DriftBase { kind: 'run'; setupId: string; sessionId: string; settingsConfirmed: boolean; identity: DriftIdentity; otherSettings: string; tires: string; conditions: string; driverAssists: string; event: DriftEvent }
export interface Distribution { observedSeconds: number; mean: number | null; p05: number | null; p50: number | null; p95: number | null }
export interface DriftSummary extends DriftBase { kind: 'summary'; runId: string; sessionId: string; recording: { endReason: string; droppedSamples?: number; failedWrites?: number; incompletePersistence?: boolean }; observations: { sampleCount: number; quality: { observedSeconds: number; gapSeconds: number }; yawRate: { distribution: Distribution; highYawEvents: { count: number | null; seconds: number | null }; note: string }; sideslipProxy: { rearMinusFrontSlipDistribution: Distribution; sustainedSlideEvents: { count: number | null; seconds: number | null }; note: string }; wheels: Record<string, { temperatureC: Distribution; slipRatio: Distribution }>; unmodeledVariables: string[]; limitationNote: string } }
export interface DriftFinish extends DriftBase { kind: 'finish'; runId: string; score: number; durationSeconds: number; source: string }
export interface DriftReport extends DriftBase { kind: 'comparison'; baselineRunIds: string[]; candidateRunIds: string[]; baselineSetupId: string; candidateSetupId: string; conclusion: string; conclusionNote: string; reasons: string[]; methodVersion: string; evidenceLevel: string; independentRuns: { baseline: number; candidate: number }; driftMetrics: { baselineScores: number[]; candidateScores: number[]; deltaScore: number | null; baselineMeanYawRateRads: number[]; candidateMeanYawRateRads: number[]; deltaYawRateRads: number | null }; limitations: string[] }
export interface DriftDecision extends DriftBase { kind: 'decision'; reportId: string; choice: string; setupId: string; status: string }
export interface DriftFeedback extends DriftBase { kind: 'feedback'; baselineRunId: string; hypothesis: string; source: string; baselineSetupId: string }
export type DriftDocument = DriftWorkflow | DriftSetup | DriftRun | DriftSummary | DriftFinish | DriftReport | DriftDecision | DriftFeedback;
export interface DriftLive { identity: DriftIdentity | null; fresh: boolean; source: string; activeRun: { id: string; workflowId: string } | null; sampleCount: number; state: string; error: string | null }
export const documentsOf = <K extends DriftDocument['kind']>(docs: DriftDocument[], kind: K) => docs.filter((d): d is Extract<DriftDocument, { kind: K }> => d.kind === kind);
