export interface OffroadIdentity { ordinal: number; performanceIndex: number; drivetrain: number }
export interface OffroadEvent { name: string; format: 'circuit' | 'sprint'; driverAssists: string; conditions: string }
export interface OffroadBase { id: string; workflowId: string; createdAt: number; schema: 'offroad-workflow/v1' }
export interface OffroadWorkflow extends OffroadBase { kind: 'workflow'; identity: OffroadIdentity; identitySource: string; carName: string; configuration: string; event: OffroadEvent }
export interface OffroadSetting { value: number; unit: string; minimum: number; maximum: number; step: number; source: string }
export interface OffroadSetup extends OffroadBase { kind: 'setup'; label: string; fields: Record<string, OffroadSetting>; confirmationScope: string; source: string; baselineSetupId: string | null; basisSetupId?: string; basisRunId?: string; targetParameter?: string; status?: string }
export interface OffroadRun extends OffroadBase { kind: 'run'; setupId: string; sessionId: string; settingsConfirmed: boolean; identity: OffroadIdentity; otherSettings: string; tires: string; conditions: string; driverAssists: string }
export interface Distribution { observedSeconds: number; mean: number | null; p05: number | null; p50: number | null; p95: number | null }
export interface OffroadWheel { temperatureC: Distribution; startTemperatureC: number | null; endTemperatureC: number | null; temperatureChangeC: number | null; normalizedTravel: Distribution; travelMeters: Distribution; peakTravelPct: number | null; nearCompression: { count: number | null; seconds: number | null }; severeBottoming: { count: number | null; seconds: number | null }; nearExtension: { count: number | null; seconds: number | null } }
export interface OffroadSummary extends OffroadBase { kind: 'summary'; runId: string; sessionId: string; recording: { endReason: string; droppedSamples?: number; failedWrites?: number; incompletePersistence?: boolean }; observations: { sampleCount: number; quality: { observedSeconds: number; gapSeconds: number }; wheels: Record<string, OffroadWheel>; airborne: { count: number; totalAirtimeSeconds: number; longestAirtimeSeconds: number }; landing: { maxImpactG: number | null; averageImpactG: number | null }; terrain: { surfaceRoughnessRms: number; pitchStdDevDeg: number; rollStdDevDeg: number }; laps: { lapNumber: number; complete: boolean; lapTimeSeconds: number | null; lapTimeSource: string }[]; sprint: { observedSpanSeconds: number | null; distanceTraveledMeters: number | null; maxSpeedKmh: number | null; meanSpeedKmh: number | null } } }
export interface OffroadFinish extends OffroadBase { kind: 'finish'; runId: string; timeSeconds: number; clean: string; source: string }
export interface OffroadReport extends OffroadBase { kind: 'comparison'; baselineRunIds: string[]; candidateRunIds: string[]; baselineSetupId: string; candidateSetupId: string; conclusion: string; reasons: string[]; methodVersion: string; evidenceLevel: string; independentRuns: { baseline: number; candidate: number }; time: { medianChangeSeconds: number | null; baselineSeconds: number[]; candidateSeconds: number[]; repeatedDirectionConsistent: boolean }; offroadMetrics: { baselineBottomingCount: number; candidateBottomingCount: number; bottomingCountChange: number; baselineBottomingSeconds: number; candidateBottomingSeconds: number; bottomingSecondsChange: number; baselineLandingImpactG: number | null; candidateLandingImpactG: number | null; landingImpactGChange: number | null; baselineRoughnessRms: number; candidateRoughnessRms: number; roughnessRmsChange: number }; thermalStart: { status: string; changeC: (number | null)[] }; local: { segments?: OffroadSegment[]; routeStatus: string; baselineCoverage: number; candidateCoverage: number; matchedDrivingConditions: number; meanNormalizedAngleChange: number | null }; limitations: string[] }
export interface OffroadSegment { index: number; fromMeters: number; toMeters: number; matchedLocations: number; angleLocations: number; meanNormalizedAngleChange: number | null; meanTemperatureChangeC: (number | null)[] }
export interface OffroadDecision extends OffroadBase { kind: 'decision'; reportId: string; choice: string; setupId: string; status: string }
export interface OffroadFeedback extends OffroadBase { kind: 'feedback'; baselineRunId: string; hypothesis: string; source: string; baselineSetupId: string }
export interface OffroadVehicleInputs extends OffroadBase { kind: 'vehicle-inputs'; fields: Record<string, { value: number; unit: string; source: string }>; confirmationScope: string }
export type OffroadDocument = OffroadWorkflow | OffroadSetup | OffroadRun | OffroadSummary | OffroadFinish | OffroadReport | OffroadDecision | OffroadFeedback | OffroadVehicleInputs;
export interface OffroadLive { identity: OffroadIdentity | null; fresh: boolean; source: string; activeRun: { id: string; workflowId: string } | null; sampleCount: number; state: string; error: string | null }
export const documentsOf = <K extends OffroadDocument['kind']>(docs: OffroadDocument[], kind: K) => docs.filter((d): d is Extract<OffroadDocument, { kind: K }> => d.kind === kind);
