export interface DragIdentity { ordinal: number; performanceIndex: number; drivetrain: number }
export interface DragBase { id: string; workflowId: string; createdAt: number; schema: 'drag-workflow/v1' }
export interface DragWorkflow extends DragBase { kind: 'workflow'; identity: DragIdentity; identitySource: string; carName: string; configuration: string; eventName: string; driverAssists: string }
export interface DragSetting { value: number; unit: string; minimum: number; maximum: number; step: number; source: string }
export interface DragSetup extends DragBase { kind: 'setup'; label: string; fields: Record<string, DragSetting>; confirmationScope: string; source: string; baselineSetupId: string | null; basisSetupId?: string; basisRunId?: string; targetParameter?: string; status?: string }
export interface DragRun extends DragBase { kind: 'run'; setupId: string; sessionId: string; settingsConfirmed: boolean; identity: DragIdentity; otherSettings: string; tires: string; driverAssists: string; eventName: string }
export interface Distribution { observedSeconds: number; mean: number | null; p05: number | null; p50: number | null; p95: number | null }
export interface DragSummary extends DragBase { kind: 'summary'; runId: string; sessionId: string; recording: { endReason: string; droppedSamples?: number; failedWrites?: number; incompletePersistence?: boolean }; observations: { sampleCount: number; quality: { observedSeconds: number; gapSeconds: number }; launch: { peakSlipRatio: number | null; meanSlipRatio: number | null; wheelspinDurationSeconds: number; sampleCount: number }; gearCurves: { gear: number; meanSpeedKmh: number | null; meanAccelerationMss: number | null; sampleCount: number }[]; shifts: { fromGear: number; toGear: number; rpmBefore: number; rpmAfter: number; rpmDrop: number; rpmRetentionRatio: number | null; shiftDurationSeconds: number }[]; milestones: { zeroTo100KmhSeconds: number | null; zeroTo200KmhSeconds: number | null; zeroTo400mSeconds: number | null }; speed: Distribution; engineRpm: Distribution; maxSpeedKmh: number | null } }
export interface DragFinish extends DragBase { kind: 'finish'; runId: string; timeSeconds: number; clean: string; source: string }
export interface DragReport extends DragBase { kind: 'comparison'; baselineRunIds: string[]; candidateRunIds: string[]; baselineSetupId: string; candidateSetupId: string; conclusion: string; reasons: string[]; methodVersion: string; evidenceLevel: string; independentRuns: { baseline: number; candidate: number }; time: { medianChangeSeconds: number | null; baselineSeconds: number[]; candidateSeconds: number[]; repeatedDirectionConsistent: boolean }; dragMetrics: { baseline0To100Seconds: number[]; candidate0To100Seconds: number[]; delta0To100Seconds: number | null; baseline0To400mSeconds: number[]; candidate0To400mSeconds: number[]; delta0To400mSeconds: number | null; baselineLaunchPeakSlip: number[]; candidateLaunchPeakSlip: number[]; deltaLaunchPeakSlip: number | null }; limitations: string[] }
export interface DragDecision extends DragBase { kind: 'decision'; reportId: string; choice: string; setupId: string; status: string }
export interface DragFeedback extends DragBase { kind: 'feedback'; baselineRunId: string; hypothesis: string; source: string; baselineSetupId: string }
export type DragDocument = DragWorkflow | DragSetup | DragRun | DragSummary | DragFinish | DragReport | DragDecision | DragFeedback;
export interface DragLive { identity: DragIdentity | null; fresh: boolean; source: string; activeRun: { id: string; workflowId: string } | null; sampleCount: number; state: string; error: string | null }
export const documentsOf = <K extends DragDocument['kind']>(docs: DragDocument[], kind: K) => docs.filter((d): d is Extract<DragDocument, { kind: K }> => d.kind === kind);
